<!--
    Header for examples. Will get copied by grunt examples, and get 
    built by grunt usemin
-->
<!doctype html>
<html>
<head>
    <title>Pundit 2 examples</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Pundit 2">
    <meta name="viewport" content="width=device-width">

    <!-- TODO: Place favicon.ico and apple-touch-icon.png in the root directory -->

    <!-- build:css css/pundit-examples.css -->
    <link rel="stylesheet" href="src/pundit-examples.css">
    <!-- endbuild -->

    <!-- build:css css/pundit.css -->
    <link rel="stylesheet" href="../css/style.css">
    <link rel="stylesheet" href="../css/pundit2.css">
    <link rel="stylesheet" href="../css/korboee.css">
    <!-- endbuild -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    
</head>
<body>
    <header class="examples pnd-wrp">
        <h2>Pundit 2 examples</h2>
    </header>
