<!--
    List of all of js libraries inclues. Will get copied as is by grunt
    examples and get built by usemin.

    This is the only place where it is needed to add new files.
-->

    <!-- build:js scripts/libs.js -->
    <script src="../../bower_components/jquery/dist/jquery.js" type="text/javascript" charset="utf-8"></script>
    <script src="../../bower_components/angular/angular.js" type="text/javascript" charset="utf-8"></script>
    <script src="../../bower_components/angular-resource/angular-resource.js" type="text/javascript" charset="utf-8"></script>
    <script src="../../bower_components/angular-mocks/angular-mocks.js" type="text/javascript" charset="utf-8"></script>
    <script src="../../bower_components/angular-strap/dist/angular-strap.js" type="text/javascript" charset="utf-8"></script>
    <script src="../../bower_components/angular-strap/dist/angular-strap.tpl.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="../../bower_components/angular-animate/angular-animate.js" type="text/javascript" charset="utf-8"></script>
    <script src="../../bower_components/angular-sanitize/angular-sanitize.js" type="text/javascript" charset="utf-8"></script>
    <script src="../../bower_components/bootstrap/dist/js/bootstrap.min.js" type="text/javascript" charset="utf-8"></script>
    <!-- endbuild -->
