<!--
    List of all of pundit js includes. Will get copied as is by grunt
    examples and get built by usemin.

    This is the only place where it is needed to add new files.
-->

    <!-- build:js scripts/pundit2.js -->
    <script src="../src/templates.js"></script>

    <script src="../src/pundit2.js"></script>

    <script src="../src/AnnomaticModule/AnnomaticModule.js"></script>
    <script src="../src/AnnomaticModule/annomatic-panel.dir.js"></script>
    <script src="../src/AnnomaticModule/annomatic-panel.ctrl.js"></script>
    <script src="../src/AnnomaticModule/annotate.service.js"></script>
    <script src="../src/AnnomaticModule/datatxt-resource.factory.js"></script>
    <script src="../src/AnnomaticModule/annotation-popover.ctrl.js"></script>
    <script src="../src/AnnomaticModule/automatic-annotation.ctrl.js"></script>

    <script src="../src/demo.ctrl.js"></script>
    <!-- endbuild -->